server:
  port: 7003
spring:
  application:
    name: gmall-bussiness-pms
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        group: gmall
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.159.128:3306/gmall_pms?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
  jpa:
    show-sql: true
    generate-ddl: true
